name: webalea_env
channels:
  - openalea3        # Priority to OpenAlea packages
  - conda-forge
  - defaults
dependencies:
  - python>=3.10,<3.13   # Flexible between 3.10 and 3.12
  - fastapi
  - uvicorn
  - pydantic
  - pydantic-settings
  - aiofiles
  - packaging
  - setuptools
  - openalea.plantgl
  - openalea.widgets