name: React Flow linting

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: webAleaFront
        run: npm ci

      # linting
      - name: Run ESLint
        working-directory: webAleaFront
        run: npx eslint . --ext .js,.jsx,.ts,.tsx

      # testing
      - name: Run tests with coverage
        working-directory: webAleaFront
        run: npm test -- --coverage --watchAll=false

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: webAleaFront/coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true